### ISSUE TITLE
change float to include max value, add optional parameter for excluding it

### ISSUE THREAD

**Issue by ValerioCipolla** [ValerioCipolla/vrandom#38]

**Comment by kennarddh** [comment]
It is imposible [link](https://stackoverflow.com/questions/33167339/generate-random-numbers-in-specified-range-various-cases-int-float-inclusiv)?

**Comment by ValerioCipolla** [comment]
yes i was reading about it yesterday, apparently it is. I'll leave it like it is and delete this issue for the moment. I might come up with a different idea at some point. Thank you.
